### ISSUE TITLE
Returning interface from Service

### ISSUE THREAD

**Issue by shobensack0** [Expecho/ServiceFabric-Remoting-CustomHeaders#4]
Is there any way to return interfaces from services? After running the demo project, returning concrete classes seems to work but I get a serialization exception when using an interface.

![image](https://user-images.githubusercontent.com/2830058/42343471-2d478ff2-8067-11e8-89b3-81dc725841e4.png)

**Comment by Expecho** [comment]
Can you tell me more about the changes you made? Am I correct to say you changed the return type of SayHelloToActor to `async Task<IList<string>> SayHelloToActor()`?

**Comment by shobensack0** [comment]
We took the sample project and changed it from returning Task\<string\> to Task\<IEnumerable\<string\>\>. Attached are the changes:

![upload200](https://user-images.githubusercontent.com/2830058/42379619-439d0d76-80f9-11e8-9177-f93810d61229.png)

![upload300](https://user-images.githubusercontent.com/2830058/42379620-43ad443e-80f9-11e8-9681-ecacb21e4e81.png)

I'm curious if this package is compatible with the [remoting V2 changes made by Microsoft?](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting#how-to-use-custom-serialization-with-remoting-v2) I think this may be where the problem may be.

**Comment by Expecho** [comment]
This package does support remoting V2, in fact, it only support V2, and not V1.

Basically the V2 remoting stack by default disallows interfaces, as stated [here](https://github.com/Azure/service-fabric-issues/issues/497#issuecomment-333686436):

> Scenario is by default , Remoting Api Types needs to be of concrete Type. In above case , if you change type IEnumerable to long[] , it will work. By default , we take serialization knowntypes from the Api return/response types.

Either you use `async Task<List<string>>` or you create your own  serialization provider. This package can still be used as you can inject in the `FabricTransportServiceRemotingClientFactory`

```csharp

IServiceRemotingMessageSerializationProvider serializationProvider = // create your custom provider here;
            var proxyFactory = new ServiceProxyFactory(handler =>
                new ExtendedServiceRemotingClientFactory(
                    new FabricTransportServiceRemotingClientFactory(serializationProvider: serializationProvider, 
                        remotingCallbackMessageHandler: handler), customHeadersProvider)
```

Anyway, the problem has nothing to do with the packages as the same error would occur without it, if using the remoting V2 stack.

**Comment by shobensack0** [comment]
Okay gotcha, will look into making changes to the custom microsoft serializer. Thanks!
