### ISSUE TITLE
Need to upgrade ServiceFabric references to 3.2.176

### ISSUE THREAD

**Issue by johnds1974** [Expecho/ServiceFabric-Remoting-CustomHeaders#6]
V3.0.9 currently uses SF 3.2.162, which causes all sorts of glorious SerializationExceptions when making remoting calls. 

When NOT using CustomHeaders, using either SF 3.2.162 or 3.2.176 (latest) these issues do not occur. So I'm only asuming that if CustomHeaders were to use 3.2.176 then perhaps these problems would also go away?

**Comment by mfmadsen** [comment]
I'm using SF 3.2.176 and have no issues with v3.0.9 of this package. What are the headers you're trying to send?
